In [44]:
import os
import pandas as pd

DATA_DIR = "data"
FOLDERS = ["olha", "daria_z", "robert"]

events = []

for person in FOLDERS:
    person_path = os.path.join(DATA_DIR, person)

    for root, _, files in os.walk(person_path):
        for file in files:
            if file.endswith("events.csv"):   # or file == "events.csv"
                csv_path = os.path.join(root, file)

                df = pd.read_csv(csv_path)

                df["participant"] = person
                df["events_file"] = csv_path.replace("\\", "/")

                events.append(df)

events_df = pd.concat(events, ignore_index=True)

events_df

,key,event_type,timestamp,label,participant,events_file
0,s,Start,10:17:24.270013,Stroop,olha,data/olha/session3_arm_GOOD/polar/olha3.events...
1,s,Stop,10:20:58.573841,Stroop,olha,data/olha/session3_arm_GOOD/polar/olha3.events...
2,r,Start,10:23:02.464375,Reaction,olha,data/olha/session3_arm_GOOD/polar/olha3.events...
3,r,Stop,10:24:50.287875,Reaction,olha,data/olha/session3_arm_GOOD/polar/olha3.events...
4,n,Start,10:26:57.561817,N-Back,olha,data/olha/session3_arm_GOOD/polar/olha3.events...
...,...,...,...,...,...,...
57,s,Stop,15:23:24.777738,Stroop,robert,data/robert/session7/polar/robert_2emotibit1.e...
58,r,Start,15:26:30.734176,Reaction,robert,data/robert/session7/polar/robert_2emotibit1.e...
59,r,Stop,15:28:41.627848,Reaction,robert,data/robert/session7/polar/robert_2emotibit1.e...
60,n,Start,15:31:50.721942,N-Back,robert,data/robert/session7/polar/robert_2emotibit1.e...
61,n,Stop,15:35:49.431433,N-Back,robert,data/robert/session7/polar/robert_2emotibit1.e...

In [45]:
import datetime
def parse_log_datetime(dt_str):
    # dt_str: '2026-04-15 11:03:30.647'
    return datetime.datetime.strptime(dt_str, "%Y-%m-%d %H:%M:%S.%f")
def extract_time(value):
    if pd.isna(value):
        return pd.NA
    text = str(value).strip()
    if not text:
        return pd.NA
    return text.split()[-1]
def timestamp_to_seconds(ts):
    # Handles missing values and strings like '11:07:23.359275'
    if pd.isna(ts):
        return pd.NA
    ts = str(ts).strip()
    if not ts:
        return pd.NA
    time_part, _, fraction = ts.partition(".")
    t = datetime.datetime.strptime(time_part, "%H:%M:%S")
    ms = float(f"0.{fraction}") if fraction else 0
    return t.hour * 3600 + t.minute * 60 + t.second + ms
events_df['prefix'] = events_df.iloc[:, 0].str.split('/').str[0]
#save only time without date
# events_df['time'] = events_df['timestamp'].apply(extract_time)
# events_df['Timestamp'] = events_df['time'].apply(timestamp_to_seconds)
events_df['Timestamp'] = events_df['timestamp']
events_df

,key,event_type,timestamp,label,participant,events_file,prefix,Timestamp
0,s,Start,10:17:24.270013,Stroop,olha,data/olha/session3_arm_GOOD/polar/olha3.events...,s,10:17:24.270013
1,s,Stop,10:20:58.573841,Stroop,olha,data/olha/session3_arm_GOOD/polar/olha3.events...,s,10:20:58.573841
2,r,Start,10:23:02.464375,Reaction,olha,data/olha/session3_arm_GOOD/polar/olha3.events...,r,10:23:02.464375
3,r,Stop,10:24:50.287875,Reaction,olha,data/olha/session3_arm_GOOD/polar/olha3.events...,r,10:24:50.287875
4,n,Start,10:26:57.561817,N-Back,olha,data/olha/session3_arm_GOOD/polar/olha3.events...,n,10:26:57.561817
...,...,...,...,...,...,...,...,...
57,s,Stop,15:23:24.777738,Stroop,robert,data/robert/session7/polar/robert_2emotibit1.e...,s,15:23:24.777738
58,r,Start,15:26:30.734176,Reaction,robert,data/robert/session7/polar/robert_2emotibit1.e...,r,15:26:30.734176
59,r,Stop,15:28:41.627848,Reaction,robert,data/robert/session7/polar/robert_2emotibit1.e...,r,15:28:41.627848
60,n,Start,15:31:50.721942,N-Back,robert,data/robert/session7/polar/robert_2emotibit1.e...,n,15:31:50.721942
61,n,Stop,15:35:49.431433,N-Back,robert,data/robert/session7/polar/robert_2emotibit1.e...,n,15:35:49.431433

In [ ]:
import os
from collections import defaultdict

DATA_DIR = "data"

FOLDERS = ["olha", "daria_z", "robert"]

suffix_files = defaultdict(list)

for person in FOLDERS:
    person_path = os.path.join(DATA_DIR, person)

    for root, _, files in os.walk(person_path):

        if os.path.basename(root) != "polar": #POLAR ONLY
            continue

        for file in files:
            if (
                file.endswith(".csv")
                and ("_ecg_h10" in file)
                #and ("_hr_rr_h10" in file or "_hr_rr_oh1" in file)
            ):
                full_path = os.path.join(root, file)
                suffix_files[person].append(full_path)

                print(f"Found: {full_path}")

Found: data\olha\session3_arm_GOOD\polar\olha3_polar_session_ecg_h10.csv
Found: data\olha\session4_arm_GOOD\polar\olha_2emotibit1_polar_session_ecg_h10.csv
Found: data\olha\session5\polar\olha_2emotibit2_polar_session_ecg_h10.csv
Found: data\olha\session6\polar\olha_2emotibit3_polar_session_ecg_h10.csv
Found: data\daria_z\session3_arm_OKAY_two_nbacks\polar\dariaz3_polar_session_ecg_h10.csv
Found: data\daria_z\session4_wrist_GOOD\polar\dariaz_wrist_volar_polar_session_ecg_h10.csv
Found: data\daria_z\session7\polar\dariaz_2emotibit3_polar_session_ecg_h10.csv
Found: data\robert\session3_arm_OKAY_short_rests\polar\robert3_polar_session_ecg_h10.csv
Found: data\robert\session5_wrist_GOOD\polar\robert_oh1volar_emotivolar_polar_session_ecg_h10.csv
Found: data\robert\session7\polar\robert_2emotibit1_polar_session_ecg_h10.csv

In [63]:
suffix_files

defaultdict(list,
            {'olha': ['data\\olha\\session3_arm_GOOD\\polar\\olha3_polar_session_ecg_h10.csv',
              'data\\olha\\session4_arm_GOOD\\polar\\olha_2emotibit1_polar_session_ecg_h10.csv',
              'data\\olha\\session5\\polar\\olha_2emotibit2_polar_session_ecg_h10.csv',
              'data\\olha\\session6\\polar\\olha_2emotibit3_polar_session_ecg_h10.csv'],
             'daria_z': ['data\\daria_z\\session3_arm_OKAY_two_nbacks\\polar\\dariaz3_polar_session_ecg_h10.csv',
              'data\\daria_z\\session4_wrist_GOOD\\polar\\dariaz_wrist_volar_polar_session_ecg_h10.csv',
              'data\\daria_z\\session7\\polar\\dariaz_2emotibit3_polar_session_ecg_h10.csv'],
             'robert': ['data\\robert\\session3_arm_OKAY_short_rests\\polar\\robert3_polar_session_ecg_h10.csv',
              'data\\robert\\session5_wrist_GOOD\\polar\\robert_oh1volar_emotivolar_polar_session_ecg_h10.csv',
              'data\\robert\\session7\\polar\\robert_2emotibit1_polar_session_ecg_h10.csv']})

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
def get_participant_session(path):
    """Extract 'USER NAME' and 'SESSION NUMBER' from a path"""
    path = path.replace('\\', '/')
    parts = [p for p in path.split('/') if p]
    idx = parts.index('data')
    participant = parts[idx + 1]
    session = parts[idx + 2]
    return participant, session

def to_time_datetime(values):
    return pd.to_datetime(values, format='%H:%M:%S.%f', errors='coerce')

def standardize_series(series):
    values = pd.to_numeric(series, errors='coerce')
    mean_value = values.mean()
    std_value = values.std(ddof=0)
    if pd.isna(std_value) or std_value == 0:
        return values - mean_value
    return (values - mean_value) / std_value

def find_local_peaks(values, threshold=None):
    values = np.asarray(values, dtype=float)
    if values.size < 3:
        return np.array([], dtype=int)
    if threshold is None:
        threshold = values.mean() + 0.5 * values.std(ddof=0)
    middle = values[1:-1]
    peak_mask = (middle > values[:-2]) & (middle >= values[2:]) & (middle >= threshold)
    return np.where(peak_mask)[0] + 1

def summarize_ecg_window(window, participant, session, sensor, source_file, value_col='ECG_uV_std'):
    ecg = pd.to_numeric(window[value_col], errors='coerce').dropna().astype(float)
    if ecg.empty:
        return None

    time_values = window.loc[ecg.index, 'Timestamp_dt']
    start_time = time_values.iloc[0]
    end_time = time_values.iloc[-1]
    duration_s = (end_time - start_time).total_seconds() if pd.notna(start_time) and pd.notna(end_time) else np.nan

    ecg_values = ecg.to_numpy()
    ecg_diff = np.diff(ecg_values) if ecg_values.size > 1 else np.array([], dtype=float)
    peaks = find_local_peaks(ecg_values)

    q25 = float(np.percentile(ecg_values, 25))
    q75 = float(np.percentile(ecg_values, 75))
    label_values = window['label'].dropna()
    label = label_values.mode().iloc[0] if not label_values.empty else 'REST'
    return {
        'participant': participant,
        'session': session,
        'sensor': sensor,
        'label': label,
        'source_file': source_file,
        'window_start': start_time,
        'window_end': end_time,
        'duration_s': duration_s,
        'n_samples': int(ecg_values.size),
        'ecg_mean': float(np.mean(ecg_values)),
        'ecg_std': float(np.std(ecg_values, ddof=0)),
        'ecg_min': float(np.min(ecg_values)),
        'ecg_max': float(np.max(ecg_values)),
        'ecg_range': float(np.max(ecg_values) - np.min(ecg_values)),
        'ecg_median': float(np.median(ecg_values)),
        'ecg_q25': q25,
        'ecg_q75': q75,
        'ecg_iqr': float(q75 - q25),
        'ecg_rms': float(np.sqrt(np.mean(np.square(ecg_values)))),
        'ecg_energy': float(np.sum(np.square(ecg_values))),
        'ecg_mad': float(np.mean(np.abs(ecg_values - np.mean(ecg_values)))),
        'ecg_abs_diff_mean': float(np.mean(np.abs(ecg_diff))) if ecg_diff.size else np.nan,
        'ecg_abs_diff_std': float(np.std(np.abs(ecg_diff), ddof=0)) if ecg_diff.size else np.nan,
        'ecg_line_length': float(np.sum(np.abs(ecg_diff))) if ecg_diff.size else 0.0,
        'ecg_peak_count': int(peaks.size),
        'ecg_peak_rate': float(peaks.size / duration_s) if duration_s and duration_s > 0 else np.nan,
        'ecg_peak_mean': float(np.mean(ecg_values[peaks])) if peaks.size else np.nan,
        'ecg_peak_std': float(np.std(ecg_values[peaks], ddof=0)) if peaks.size else np.nan,
    }


# Build Start/Stop intervals per (participant, session, label)
def build_intervals(group):
    group = group.sort_values('Timestamp_dt')
    starts = group[group['event_type'] == 'Start']
    intervals = []
    for _, srow in starts.iterrows():
        stops = group[(
            (group['event_type'] == 'Stop')
            & (group['label'] == srow['label'])
            & (group['Timestamp_dt'] > srow['Timestamp_dt'])
        )]
        if not stops.empty:
            stop_ts = stops.iloc[0]['Timestamp_dt']
            intervals.append((srow['Timestamp_dt'], stop_ts, srow['label']))
    return intervals

# PREPROC

In [ ]:


WINDOW_SECONDS = 60
STEP_SECONDS = 10


events_df[['participant_key', 'session_key']] = events_df['events_file'].apply(
    lambda x: pd.Series(get_participant_session(x))
)
events_df['Timestamp_dt'] = to_time_datetime(events_df['Timestamp'])



intervals_by_group = {
    key: build_intervals(grp)
    for key, grp in events_df.groupby(['participant_key', 'session_key'])
}

# sliding-window features
os.makedirs('features', exist_ok=True)
ecg_feature_frames = []
labeled_signals = {}  

for participant, files in suffix_files.items():
    for f in files:
        print(f"Processing {f}...")
        p, s = get_participant_session(f)
        intervals = intervals_by_group.get((p, s), [])

        sig_df = pd.read_csv(f)
        timestamp_col = 'Packet_Timestamp'
        sig_df = sig_df.copy()
        sig_df['Timestamp_dt'] = to_time_datetime(sig_df[timestamp_col])
        sig_df['ECG_uV_std'] = standardize_series(sig_df['ECG_uV'])

        if intervals:
            starts, stops, labels = zip(*intervals)
            idx = pd.IntervalIndex.from_arrays(starts, stops, closed='both')
            positions = idx.get_indexer(sig_df['Timestamp_dt'])
            sig_df['label'] = [labels[pos] if pos != -1 else 'REST' for pos in positions]
        else:
            sig_df['label'] = 'REST'

        labeled_signals[f] = sig_df

        filename = os.path.basename(f)
        filename_no_ext = os.path.splitext(filename)[0]
        sensor = filename_no_ext[-3:]  # 'h10' or 'oh1'

        labeled_rows = sig_df[sig_df['label'].notna()].copy().sort_values('Timestamp_dt')
        if labeled_rows.empty:
            continue

        window_rows = []
        window_start = labeled_rows['Timestamp_dt'].iloc[0]
        window_end_limit = labeled_rows['Timestamp_dt'].iloc[-1] - pd.Timedelta(seconds=WINDOW_SECONDS)

        while window_start <= window_end_limit:
            window_end = window_start + pd.Timedelta(seconds=WINDOW_SECONDS)
            window = labeled_rows[(
                labeled_rows['Timestamp_dt'] >= window_start
            ) & (
                labeled_rows['Timestamp_dt'] < window_end
            )]

            if not window.empty:
                summary = summarize_ecg_window(window, p, s, sensor, f, value_col='ECG_uV_std')
                if summary is not None:
                    window_rows.append(summary)

            window_start += pd.Timedelta(seconds=STEP_SECONDS)

        features_df = pd.DataFrame(window_rows)
        if not features_df.empty:
            ecg_feature_frames.append(features_df)
            features_df.to_csv(f"features/{p}_{s}__{sensor}_ecg_features.csv", index=False)

ecg_features_df = pd.concat(ecg_feature_frames, ignore_index=True) if ecg_feature_frames else pd.DataFrame()
ecg_features_df

Processing data\olha\session3_arm_GOOD\polar\olha3_polar_session_ecg_h10.csv...
Processing data\olha\session4_arm_GOOD\polar\olha_2emotibit1_polar_session_ecg_h10.csv...
Processing data\olha\session5\polar\olha_2emotibit2_polar_session_ecg_h10.csv...
Processing data\olha\session6\polar\olha_2emotibit3_polar_session_ecg_h10.csv...
Processing data\daria_z\session3_arm_OKAY_two_nbacks\polar\dariaz3_polar_session_ecg_h10.csv...
Processing data\daria_z\session4_wrist_GOOD\polar\dariaz_wrist_volar_polar_session_ecg_h10.csv...
Processing data\daria_z\session7\polar\dariaz_2emotibit3_polar_session_ecg_h10.csv...
Processing data\robert\session3_arm_OKAY_short_rests\polar\robert3_polar_session_ecg_h10.csv...
Processing data\robert\session5_wrist_GOOD\polar\robert_oh1volar_emotivolar_polar_session_ecg_h10.csv...
Processing data\robert\session7\polar\robert_2emotibit1_polar_session_ecg_h10.csv...

,participant,session,sensor,label,source_file,window_start,window_end,duration_s,n_samples,ecg_mean,...,ecg_rms,ecg_energy,ecg_mad,ecg_abs_diff_mean,ecg_abs_diff_std,ecg_line_length,ecg_peak_count,ecg_peak_rate,ecg_peak_mean,ecg_peak_std
0,olha,session3_arm_GOOD,h10,REST,data\olha\session3_arm_GOOD\polar\olha3_polar_...,1900-01-01 10:12:50.867080,1900-01-01 10:13:50.390654,59.523574,7811,0.040723,...,0.946202,6993.177190,0.504375,0.361549,0.828446,2823.698212,419,7.039228,2.232907,1.892458
1,olha,session3_arm_GOOD,h10,REST,data\olha\session3_arm_GOOD\polar\olha3_polar_...,1900-01-01 10:13:01.103422,1900-01-01 10:14:00.482046,59.378624,7811,0.022886,...,0.946779,7001.698934,0.503750,0.366541,0.842585,2862.688927,427,7.191140,2.232888,1.890392
2,olha,session3_arm_GOOD,h10,REST,data\olha\session3_arm_GOOD\polar\olha3_polar_...,1900-01-01 10:13:11.097623,1900-01-01 10:14:10.622211,59.524588,7811,0.024832,...,0.947225,7008.302164,0.505095,0.360217,0.824373,2813.293487,414,6.955109,2.243618,1.900138
3,olha,session3_arm_GOOD,h10,REST,data\olha\session3_arm_GOOD\polar\olha3_polar_...,1900-01-01 10:13:21.188841,1900-01-01 10:14:20.713932,59.525091,7811,0.008935,...,0.945829,6987.665014,0.505743,0.355484,0.819732,2776.333314,403,6.770254,2.265341,1.905083
4,olha,session3_arm_GOOD,h10,REST,data\olha\session3_arm_GOOD\polar\olha3_polar_...,1900-01-01 10:13:31.329142,1900-01-01 10:14:30.853694,59.524552,7811,0.015775,...,0.945955,6989.519937,0.506373,0.356217,0.819874,2782.057712,411,6.904714,2.250429,1.902106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1261,robert,session7,h10,REST,data\robert\session7\polar\robert_2emotibit1_p...,1900-01-01 15:37:11.814074,1900-01-01 15:38:11.305094,59.491020,7811,0.045425,...,1.033348,8340.648771,0.528683,0.422099,0.943997,3296.595779,410,6.891796,2.346753,2.228487
1262,robert,session7,h10,REST,data\robert\session7\polar\robert_2emotibit1_p...,1900-01-01 15:37:21.894155,1900-01-01 15:38:21.430222,59.536067,7811,0.047200,...,1.031230,8306.491303,0.526067,0.423280,0.952107,3305.819887,419,7.037751,2.335636,2.220588
1263,robert,session7,h10,REST,data\robert\session7\polar\robert_2emotibit1_p...,1900-01-01 15:37:32.019225,1900-01-01 15:38:31.015235,58.996010,7738,0.049455,...,1.025627,8139.681620,0.526742,0.424421,0.964284,3283.746938,432,7.322529,2.298111,2.177398
1264,robert,session7,h10,REST,data\robert\session7\polar\robert_2emotibit1_p...,1900-01-01 15:37:41.559508,1900-01-01 15:38:41.095827,59.536319,7811,0.049244,...,1.026102,8224.081597,0.521112,0.420240,0.958958,3282.077293,428,7.188889,2.315677,2.211707
1265,robert,session7,h10,REST,data\robert\session7\polar\robert_2emotibit1_p...,1900-01-01 15:37:51.685216,1900-01-01 15:38:51.221222,59.536006,7811,0.050855,...,1.016557,8071.796386,0.516026,0.411030,0.938323,3210.145680,421,7.071351,2.282268,2.199062

In [98]:
ecg_features_df['label'].unique()

array(['REST', 'Stroop', 'Reaction', 'N-Back'], dtype=object)

# FEATURE EXTRACTION

In [99]:
data_final = ecg_features_df.copy()
drop_cols = ['window_start', 'window_end', 'source_file', 'duration_s', 'sensor', 'n_samples']
#lable text to numeric
label_mapping = {'REST': 0, 'Stroop': 1, 'Reaction': 2, 'N-Back': 3}
data_final['label'] = data_final['label'].map(label_mapping)
data_final = data_final.drop(columns=drop_cols)

In [100]:
data_final.to_csv("ecg_features_final_standard.csv", index=False)